name: Build My Application
on: push

jobs: 
  build:
    name: Build our app
    runs-on: ubuntu-18.04
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print current Directory
        run: pwd
      - name: List Files in directory
        run: ls
      - name: Dotnet build
        run: dotnet build TrickLibrary.Api
      - name: NPM version
        run: npm --version